/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athie.call.frontEnd;

import athie.call.resorts.beans.UnitsAvailable;
import athie.call.resorts.wsdl.callWsdl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import xml.utils.BeanTableModel;
import xml.utils.ResortsXml;

/**
 *
 * @author oem
 */
public class testPanel extends javax.swing.JPanel {
    String ResortName, ResortCity, ResortCountry,TravelDate1,TravelDate2;
    callWsdl wsdl;
    List<UnitsAvailable> lstUnitsAvailable;

    /**
     * Creates new form testPanel
     */
    public testPanel() {
        lstUnitsAvailable = new ArrayList<>();
        wsdl = new callWsdl();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jlblNombre = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jlblCiudad = new javax.swing.JLabel();
        jtxtCiudad = new javax.swing.JTextField();
        jlblPais = new javax.swing.JLabel();
        jtxtPais = new javax.swing.JTextField();
        jtxtFechaInicio = new javax.swing.JTextField();
        jlblDateInit = new javax.swing.JLabel();
        jlblDateFin = new javax.swing.JLabel();
        jtxtFechaFinal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUnitsAvailable = new javax.swing.JTable();
        jbtnBuscar = new javax.swing.JButton();

        jlblNombre.setText("Nombre");
        jlblNombre.setToolTipText("");

        jtxtNombre.setToolTipText("Nombre del Resort");

        jlblCiudad.setText("Ciudad");

        jtxtCiudad.setToolTipText("Ciudad");

        jlblPais.setText("Pais");

        jtxtPais.setToolTipText("Nombre o Acronimo del pais");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtxtFechaInicio, org.jdesktop.beansbinding.ELProperty.create("${toolTipText}"), jtxtFechaInicio, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jlblDateInit.setText("Fecha Inicio");

        jlblDateFin.setText("Fecha Final");

        jtxtFechaFinal.setToolTipText("Fecha YYYY-MM-DD");

        jtblUnitsAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblUnitsAvailable);

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblPais)
                    .addComponent(jlblDateInit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCiudad)
                    .addComponent(jlblNombre)
                    .addComponent(jlblDateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtPais)
                    .addComponent(jtxtCiudad)
                    .addComponent(jtxtNombre)
                    .addComponent(jtxtFechaInicio)
                    .addComponent(jtxtFechaFinal)
                    .addComponent(jbtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblDateInit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblDateFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jbtnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        System.out.println("Buscar");
        System.out.println(jtxtPais.getText());
        ResortName = jtxtNombre.getText().isEmpty()?"":jtxtNombre.getText();
        ResortCity = jtxtCiudad.getText().isEmpty()?"":jtxtCiudad.getText();
        ResortCountry = jtxtPais.getText().isEmpty()?"":jtxtPais.getText();
        TravelDate1 = jtxtFechaInicio.getText().isEmpty()?"":jtxtFechaInicio.getText();
        TravelDate2 = jtxtFechaFinal.getText().isEmpty()?"":jtxtFechaFinal.getText();
        System.out.println(ResortName + "//" +ResortCity + "//" +ResortCountry + "//" + TravelDate1 + "//" + TravelDate2);
        getLstUnitsAvailable();
        if(lstUnitsAvailable.size() > 0){
            BeanTableModel<UnitsAvailable> btM = 
                    new BeanTableModel<UnitsAvailable>(UnitsAvailable.class,java.awt.Component.class);
            //btM.addRow(lstUnitsAvailable.toArray());
            Object[] columnNames = {
                //ResortsXml.InvType,
                ResortsXml.ResortId,
            ResortsXml.ResortName,
            ResortsXml.ResortHighLights,
            ResortsXml.ResortAddress1,
            ResortsXml.ResortAddress2,
            ResortsXml.ResortAddress3,
            ResortsXml.ResortCity,
            ResortsXml.ResortState,
            ResortsXml.ResortCountry,
            ResortsXml.ResortRegion,
            ResortsXml.ResortPhone,
            ResortsXml.UnitID,
            ResortsXml.MaxOccupancy,
            ResortsXml.PrivacyOccupancy,
            //ResortsXml.InventoryID,
            ResortsXml.CheckInDate,
            ResortsXml.CheckOutDate,
            ResortsXml.Price,
            //ResortsXml.AllInclusive,
            ResortsXml.Nights,
            ResortsXml.ImagePath,
            ResortsXml.Images};
            Object[] data = lstUnitsAvailable.toArray();
            
            
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            for (UnitsAvailable bean : lstUnitsAvailable) {
                Object args[] = {
                    //bean.getInvType(),
                    bean.getResortId(),
                    bean.getResortName(),
                    bean.getResortHighLights(),
                    bean.getResortAddress1(),
                    bean.getResortAddress2(),
                    bean.getResortAddress3(),
                    bean.getResortCity(),
                    bean.getResortState(),
                    bean.getResortCountry(),
                    bean.getResortRegion(),
                    bean.getResortPhone(),
                    bean.getUnitID(),
                    bean.getMaxOccupancy(),
                    bean.getPrivacyOccupancy(),
                    //bean.getInventoryID(),
                    bean.getCheckInDate(),
                    bean.getCheckOutDate(),
                    699,
                    //bean.getAllInclusive(),
                    bean.getNights(),
                    bean.getImagePath(),
                    bean.getImages()
                        
            };
            model.addRow(args);
        }
        jtblUnitsAvailable.setModel(model);
            //jtblUnitsAvailable.
            jtblUnitsAvailable.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
            //JScrollPane scrollPane = new JScrollPane( jtblUnitsAvailable );
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void getLstUnitsAvailable(){
         if (!(ResortName.isEmpty() && ResortCity.isEmpty() && ResortCountry.isEmpty() && TravelDate1.isEmpty() &&
                TravelDate2.isEmpty())) {
             System.out.println("Entre");
            lstUnitsAvailable = wsdl.getUnitAvailable(ResortName, ResortCity, ResortCountry, TravelDate1, TravelDate2);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JLabel jlblCiudad;
    private javax.swing.JLabel jlblDateFin;
    private javax.swing.JLabel jlblDateInit;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblPais;
    private javax.swing.JTable jtblUnitsAvailable;
    private javax.swing.JTextField jtxtCiudad;
    private javax.swing.JTextField jtxtFechaFinal;
    private javax.swing.JTextField jtxtFechaInicio;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPais;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
